=== abhinavumang/wrox/book.dtd
<!ELEMENT book (authors,title,price,keywords)>
<!ELEMENT authors (author,author)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT keywords (keyword,keyword)>
<!ELEMENT keyword (#PCDATA)>
<!ELEMENT keyword (#PCDATA)>

=== abhinavumang/wrox/external_dtd.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE book SYSTEM "book.dtd" >
<book>
  <authors>
    <author id="12">Hari Prasad</author>
    <author id="18">Hari Ram</author>
  </authors>
  <title>Database systems</title>
  <price>100</price>
  <keywords>
    <keyword>sql</keyword>
    <keyword>relational</keyword>
  </keywords>
</book>
