<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE book [
<!ELEMENT book (authors,title,price,keywords)>
<!ELEMENT authors (author,author)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT keywords (keyword,keyword)>
<!ELEMENT keyword (#PCDATA)>
<!ELEMENT keyword (#PCDATA)>
]>

<b:book xmlns:b="http://www.w3.org/2003/05/soap-envelope">
  <authors>
    <author id="12">Hari Prasad</author>
    <author id="18">Hari Ram</author>
  </authors>
  <title>Database systems</title>
  <price>100</price>
  <keywords>
    <keyword>sql</keyword>
    <keyword>relational</keyword>
  </keywords>
</b:book>